<?xml version="1.0" encoding="utf-8"?>
<test-results name="Test results" errors="0" inconclusive="0" ignored="0" invalid="0" not-run="0" date="2018-03-07" time="08:58:09" total="2" failures="1" skipped="0">
  <environment os-version="unknown" platform="unknown" cwd="unknown" machine-name="unknown" user="unknown" user-domain="unknown" nunit-version="xUnit.net 2.4.0.3958" clr-version="64-bit .NET Standard [collection-per-class, parallel (8 threads)]" />
  <culture-info current-culture="unknown" current-uiculture="unknown" />
  <test-suite type="Assemblies" name="xUnit.net Tests" executed="True" success="False" result="Failure" time="0.343">
    <results>
      <test-suite type="Assembly" executed="True" name="CITest.dll" result="Failure" success="False" time="0.343">
        <results>
          <test-suite type="TestCollection" executed="True" name="Test collection for CITest.UnitTests" result="Failure" success="False" time="0.021">
            <results>
              <test-case name="Fail test" executed="True" result="Failure" success="False" time="0.0133947">
                <failure>
                  <message>This test should fail\r\nExpected: True\r\nActual:   False</message>
                  <stack-trace>   at CITest.UnitTests.Fail_Test() in C:\Users\troja\source\repos\CITest\CITest\UnitTests.cs:line 10</stack-trace>
                </failure>
              </test-case>
              <test-case name="Pass test" executed="True" result="Success" success="True" time="0.0080248" />
            </results>
          </test-suite>
        </results>
      </test-suite>
    </results>
  </test-suite>
</test-results>